run:
  timeout: 5m
  tests: false

# output configuration options
output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - promlinter
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused

linters-settings:
  gci:
    # put imports beginning with prefix after 3rd-party packages;
    # only support one prefix
    # if not set, use goimports.local-prefixes
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.

  goconst:
    min-len: 2
    min-occurrences: 3
  gofmt:
    simplify: true
  goimports:
    local-prefixes: go.voiplens.io
  gosec:
    exclude-generated: true
    severity: high
    confidence: high
  govet:
    check-shadowing: false
    disable:
      - shadow
  misspell:
    locale: UK
    ignore-words:
      - angarium
      - authorized
      - unauthorized
      - voiplens
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  revive:
    rules:
      - name: unexported-return
        disabled: true
